services:
  backend:
    image: ${BACKEND_IMAGE:?BACKEND_IMAGE is required}
    container_name: kingstore-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    restart: unless-stopped
